export const CR = "\r";
export const LF = "\n";
export const CRLF = CR+LF;
export const ONE_SPACE = " ";
export const HASH_STRING = "#string ";
export const HASH_LANGUAGE = "#language";
export const PATTERN_STRING = new RegExp(/^#string/);
export const PATTERN_LANGUAGE = new RegExp(/^#language/); //開頭是#language
export const PATTERN_COMMENT = new RegExp(/^\/\//); //開頭是//
export const PATTERN_TWO_QUOTE = new RegExp(/("([^"]|"")*")/);
